cls
call riffstrip.exe "Four.wav"
call riffstrip.exe "Boost.wav"
call riffstrip.exe "EagleSoft_Song.wav"
call riffstrip.exe "eggmanLaugh.wav"
call riffstrip.exe "GenesisCan1.wav"
call riffstrip.exe "GenesisCan2.wav"
call riffstrip.exe "GenesisCan3.wav"
call riffstrip.exe "GenesisDoes1.pcm"
call riffstrip.exe "git-hub.wav"
call riffstrip.exe "Madness.wav"
call riffstrip.exe "MadnessR.wav"
REM call riffstrip.exe "nep.wav"
REM call riffstrip.exe "SM64_MM.wav"
call riffstrip.exe "YoFreddy.wav"

ren "Four.wav.stripped" "Four.pcm"
ren "Boost.wav.stripped" "Boost.pcm"
ren "EagleSoft_Song.wav.stripped" "EagleSoft_Song.pcm"
ren "eggmanLaugh.wav.stripped" "eggmanLaugh.pcm"
ren "GenesisCan1.wav.stripped" "GenesisCan1.pcm"
ren "GenesisCan2.wav.stripped" "GenesisCan2.pcm"
ren "GenesisCan3.wav.stripped" "GenesisCan3.pcm"
ren "GenesisDoes1.wav.stripped" "GenesisDoes1.pcm"
ren "git-hub.wav.stripped" "git-hub.pcm"
ren "Madness.wav.stripped" "Madness.pcm"
ren "MadnessR.wav.stripped" "MadnessR.pcm"
REM ren "nep.wav.stripped" "nep.pcm"
REM ren "SM64_MM.wav.stripped" "SM64_MM.pcm"
ren "YoFreddy.wav.stripped" "YoFreddy.pcm"

del /q "Four.wav.stripped"
del /q "Boost.wav.stripped"
del /q "EagleSoft_Song.wav.stripped"
del /q "eggmanLaugh.wav.stripped"
del /q "GenesisCan1.wav.stripped"
del /q "GenesisCan2.wav.stripped"
del /q "GenesisCan3.wav.stripped"
del /q "GenesisDoes1.wav.stripped"
del /q "git-hub.wav.stripped"
del /q "Madness.wav.stripped"
del /q "MadnessR.wav.stripped"
REM del /q "nep.wav.stripped"
REM del /q "SM64_MM.wav.stripped"
del /q "YoFreddy.wav.stripped"

call "..\pcm2dpcm.exe" "Four.pcm" "Four.dpcm"
call "..\pcm2dpcm.exe" "Boost.pcm" "Boost.dpcm"
call "..\pcm2dpcm.exe" "EagleSoft_Song.pcm" "EagleSoft_Song.dpcm"
call "..\pcm2dpcm.exe" "eggmanLaugh.pcm" "eggmanLaugh.dpcm"
call "..\pcm2dpcm.exe" "GenesisCan1.pcm" "GenesisCan1.dpcm"
call "..\pcm2dpcm.exe" "GenesisCan2.pcm" "GenesisCan2.dpcm"
call "..\pcm2dpcm.exe" "GenesisCan3.pcm" "GenesisCan3.dpcm"
call "..\pcm2dpcm.exe" "GenesisDoes1.pcm" "GenesisDoes1.dpcm"
call "..\pcm2dpcm.exe" "git-hub.pcm" "git-hub.dpcm"
call "..\pcm2dpcm.exe" "Madness.pcm" "Madness.dpcm"
call "..\pcm2dpcm.exe" "MadnessR.pcm" "MadnessR.dpcm"
REM call "..\pcm2dpcm.exe" "nep.pcm" "nep.dpcm"
REM call "..\pcm2dpcm.exe" "SM64_MM.pcm" "SM64_MM.dpcm"
call "..\pcm2dpcm.exe" "YoFreddy.pcm" "YoFreddy.dpcm"
pause