cls
call KENSSharp.exe -r e "ad-3ss-map.eni"
call KENSSharp.exe -r e "ad-carbuncle-map.eni"
call KENSSharp.exe -r e "ad-craig-map.eni"
call KENSSharp.exe -r e "ad-CRT-map.eni"
call KENSSharp.exe -r e "ad-deltarune-map.eni"
call KENSSharp.exe -r e "ad-eggblock-map.eni"
call KENSSharp.exe -r e "ad-ElmLab-map.eni"
call KENSSharp.exe -r e "ad-gamestar-map.eni"
call KENSSharp.exe -r e "ad-GenesisCan1-map.eni"
call KENSSharp.exe -r e "ad-GenesisCan2-map.eni"
call KENSSharp.exe -r e "ad-hong-kong-97-map.eni"
call KENSSharp.exe -r e "ad-Intel-map.eni"
call KENSSharp.exe -r e "ad-IWBTH-map.eni"
call KENSSharp.exe -r e "ad-lactose-map.eni"
call KENSSharp.exe -r e "ad-raidshadowlegends-map.eni"
call KENSSharp.exe -r e "ad-sonic-underground-map.eni"
call KENSSharp.exe -r e "ad-super-challenges-map.eni"
call KENSSharp.exe -r e "ad-TamperThingy-map.eni"
call KENSSharp.exe -r e "ad-VH-map.eni"
call KENSSharp.exe -r e "ad-willys-map.eni"
call KENSSharp.exe -r e "ad-yuri-map.eni"
call KENSSharp.exe -r e "eyecatch-map1.eni"
call KENSSharp.exe -r e "eyecatch-map2.eni"
call KENSSharp.exe -r e "Map - Support.eni"
call KENSSharp.exe -r e "Tonic Map.eni"

call KENSSharp.exe -r n "ad-3ss-art.nem"
call KENSSharp.exe -r n "ad-carbuncle-art.nem"
call KENSSharp.exe -r n "ad-craig-art.nem"
call KENSSharp.exe -r n "ad-CRT-art.nem"
call KENSSharp.exe -r n "ad-deltarune-art.nem"
call KENSSharp.exe -r n "ad-eggblock-art.nem"
call KENSSharp.exe -r n "ad-ElmLab-art.nem"
call KENSSharp.exe -r n "ad-gamestar-art.nem"
call KENSSharp.exe -r n "ad-GenesisCan1-art.nem"
call KENSSharp.exe -r n "ad-GenesisCan2-art.nem"
call KENSSharp.exe -r n "ad-hong-kong-97-art.nem"
call KENSSharp.exe -r n "ad-Intel-art.nem"
call KENSSharp.exe -r n "ad-IWBTH-art.nem"
call KENSSharp.exe -r n "ad-lactose-art.nem"
call KENSSharp.exe -r n "ad-raidshadowlegends-art.nem"
call KENSSharp.exe -r n "ad-sonic-underground-art.nem"
call KENSSharp.exe -r n "ad-super-challenges-art.nem"
call KENSSharp.exe -r n "ad-TamperThingy-art.nem"
call KENSSharp.exe -r n "ad-VH-art.nem"
call KENSSharp.exe -r n "ad-willys-art.nem"
call KENSSharp.exe -r n "ad-yuri-art.nem"
call KENSSharp.exe -r n "Art - Support.nem"
call KENSSharp.exe -r n "eyecatch-art.nem"
call KENSSharp.exe -r n "Tonic Art.nem"
REM pause